apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name}}
spec:
  serviceName: {{.Values.service.name}}
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.label}}
  template:
    metadata:
      labels:
        app: {{.Values.label}}
    spec:
      containers:
        - name: {{ .Values.name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name}}
