spring:
  application:
    name: teacher-service


  datasource:
    url: jdbc:postgresql://localhost:5435/postgrescicdDB
    username: postgrescicd
    password: postgrescicd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true