apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}